---
platform: emscripten 
generator: Ninja
build_tool: vscode_cmake 
build_type: Release
cmake-toolchain: emscripten.toolchain.cmake
defines:
    FIPS_NO_ASSERTS_IN_RELEASE: ON
    FIPS_EMSCRIPTEN_USE_WASM: ON

